# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170416_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accaunt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
