# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170416_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
