# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_profile_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(default='BC123456', max_length=10),
        ),
    ]
