# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170416_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passport_number',
        ),
    ]
