# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_profile_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(default='CD1231234', max_length=10),
        ),
    ]
