# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_profile_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passport_number',
        ),
    ]
