# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_profile_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accaunt',
            field=models.BooleanField(default=False),
        ),
    ]
